#!/bin/bash
python generate.py configs/demo/demo_combined.yaml --text 'cases/display/a TV monitor'
python generate.py configs/demo/demo_combined.yaml --text 'cases/table/a glass single leg circular table' 
python generate.py configs/demo/demo_combined.yaml --text 'cases/table/a wooden double layers table'
python generate.py configs/demo/demo_combined.yaml --text 'cases/table/a square metal table'
python generate.py configs/demo/demo_combined.yaml --text 'cases/table/a round shaped single legged wooden table'
python generate.py configs/demo/demo_combined.yaml --text 'cases/chair/this is a bar stool with metal arches as a design feature'
python generate.py configs/demo/demo_combined.yaml --text 'cases/chair/a children chair with little legs'
python generate.py configs/demo/demo_combined.yaml --text 'cases/chair/a swivel chair with wheels'
python generate.py configs/demo/demo_combined.yaml --text 'cases/chair/a red recliner seems confortable'
python generate.py configs/demo/demo_combined.yaml --text 'cases/car/a red car'
python generate.py configs/demo/demo_combined.yaml --text 'cases/car/a green SUV'
python generate.py configs/demo/demo_combined.yaml --text 'cases/car/a large black truck'
python generate.py configs/demo/demo_combined.yaml --text 'cases/car/a long luxury black car'
python generate.py configs/demo/demo_combined.yaml --text 'cases/airplane/army fighter jet'
python generate.py configs/demo/demo_combined.yaml --text 'cases/airplane/a black airplane with long white wings'
python generate.py configs/demo/demo_combined.yaml --text 'cases/airplane/a blue airplane with short wings'
python generate.py configs/demo/demo_combined.yaml --text 'cases/airplane/boeing 747'
python generate.py configs/demo/demo_combined.yaml --text 'cases/watercraft/a big ship for transportation'
python generate.py configs/demo/demo_combined.yaml --text 'cases/watercraft/a boat with sail'
python generate.py configs/demo/demo_combined.yaml --text 'cases/watercraft/a watercraft'
python generate.py configs/demo/demo_combined.yaml --text 'cases/watercraft/a wooden boat'
python generate.py configs/demo/demo_combined.yaml --text 'cases/sofa/a blue sofa'
python generate.py configs/demo/demo_combined.yaml --text 'cases/sofa/sofa with legs'
python generate.py configs/demo/demo_combined.yaml --text 'cases/sofa/a sofa with black backrest'
python generate.py configs/demo/demo_combined.yaml --text 'cases/sofa/a small sofa'
python generate.py configs/demo/demo_combined.yaml --text 'cases/bench/a long brown bench'
python generate.py configs/demo/demo_combined.yaml --text 'cases/bench/a marble bench'
python generate.py configs/demo/demo_combined.yaml --text 'cases/bench/a metal bench'
python generate.py configs/demo/demo_combined.yaml --text 'cases/bench/concrete bench'
python generate.py configs/demo/demo_combined.yaml --text 'cases/rifle/a military sniper rifle with long barrel'
python generate.py configs/demo/demo_combined.yaml --text 'cases/rifle/a rifle with magazines'
python generate.py configs/demo/demo_combined.yaml --text 'cases/rifle/a short rifle'
python generate.py configs/demo/demo_combined.yaml --text 'cases/rifle/rifle shotgun'
python generate.py configs/demo/demo_combined.yaml --text 'cases/display/a computer monitor'
python generate.py configs/demo/demo_combined.yaml --text 'cases/display/a display'
python generate.py configs/demo/demo_combined.yaml --text 'cases/display/a monitor with square base'
python generate.py configs/demo/demo_combined.yaml --text 'cases/cabinet/a cabinet with cylindrical legs'
python generate.py configs/demo/demo_combined.yaml --text 'cases/cabinet/a cupboard'
python generate.py configs/demo/demo_combined.yaml --text 'cases/cabinet/a long brown cabinet'
python generate.py configs/demo/demo_combined.yaml --text 'cases/cabinet/a wardrobe'
python generate.py configs/demo/demo_combined.yaml --text 'cases/lamp/a desk lamp'
python generate.py configs/demo/demo_combined.yaml --text 'cases/lamp/bedside lamp'
python generate.py configs/demo/demo_combined.yaml --text 'cases/lamp/lamp supported by a long pillar'
python generate.py configs/demo/demo_combined.yaml --text 'cases/lamp/mushroom-like lamp'
python generate.py configs/demo/demo_combined.yaml --text 'cases/telephone/a mobile phone'
python generate.py configs/demo/demo_combined.yaml --text 'cases/telephone/a small cell phone'
python generate.py configs/demo/demo_combined.yaml --text 'cases/telephone/a mobile phone with black screen'
python generate.py configs/demo/demo_combined.yaml --text 'cases/telephone/an iphone'
python generate.py configs/demo/demo_combined.yaml --text 'cases/loudspeaker/a columnar loudspeaker'
python generate.py configs/demo/demo_combined.yaml --text 'cases/loudspeaker/a loudspeaker with metal surface'
python generate.py configs/demo/demo_combined.yaml --text 'cases/loudspeaker/a wooden loudspeaker'
python generate.py configs/demo/demo_combined.yaml --text 'cases/loudspeaker/a cylindrical loudspeaker'
