python generate.py configs/demo/demo_combined.yaml --text 'a cabinet with cylindrical legs'
python generate.py configs/demo/demo_combined.yaml --text 'a cupboard'
python generate.py configs/demo/demo_combined.yaml --text 'a long brown cabinet'
python generate.py configs/demo/demo_combined.yaml --text 'a wardrobe'
python generate.py configs/demo/demo_combined.yaml --text 'a desk lamp'
python generate.py configs/demo/demo_combined.yaml --text 'bedside lamp'
python generate.py configs/demo/demo_combined.yaml --text 'lamp supported by a long pillar'
python generate.py configs/demo/demo_combined.yaml --text 'mushroom-like lamp'
python generate.py configs/demo/demo_combined.yaml --text 'a mobile phone'
python generate.py configs/demo/demo_combined.yaml --text 'a small cell phone'
python generate.py configs/demo/demo_combined.yaml --text 'a mobile phone with black screen'
python generate.py configs/demo/demo_combined.yaml --text 'an iphone'
python generate.py configs/demo/demo_combined.yaml --text 'a columnar loudspeaker'
python generate.py configs/demo/demo_combined.yaml --text 'a loudspeaker with metal surface'
python generate.py configs/demo/demo_combined.yaml --text 'a wooden loudspeaker'
python generate.py configs/demo/demo_combined.yaml --text 'a cylindrical loudspeaker'
python generate.py configs/demo/demo_combined.yaml --text 'a TV monitor'
python generate.py configs/demo/demo_combined.yaml --text 'a glass single leg circular table' 
python generate.py configs/demo/demo_combined.yaml --text 'a wooden double layers table'
python generate.py configs/demo/demo_combined.yaml --text 'a square metal table'
python generate.py configs/demo/demo_combined.yaml --text 'a round shaped single legged wooden table'
python generate.py configs/demo/demo_combined.yaml --text 'this is a bar stool with metal arches as a design feature'
python generate.py configs/demo/demo_combined.yaml --text 'a children chair with little legs'
python generate.py configs/demo/demo_combined.yaml --text 'a swivel chair with wheels'
python generate.py configs/demo/demo_combined.yaml --text 'a red recliner seems confortable'
python generate.py configs/demo/demo_combined.yaml --text 'a red car'
python generate.py configs/demo/demo_combined.yaml --text 'a green SUV'
python generate.py configs/demo/demo_combined.yaml --text 'a large black truck'
python generate.py configs/demo/demo_combined.yaml --text 'a long luxury black car'
python generate.py configs/demo/demo_combined.yaml --text 'army fighter jet'
python generate.py configs/demo/demo_combined.yaml --text 'a black airplane with long white wings'
python generate.py configs/demo/demo_combined.yaml --text 'a blue airplane with short wings'
python generate.py configs/demo/demo_combined.yaml --text 'boeing 747'
python generate.py configs/demo/demo_combined.yaml --text 'a big ship for transportation'
python generate.py configs/demo/demo_combined.yaml --text 'a boat with sail'
python generate.py configs/demo/demo_combined.yaml --text 'a watercraft'
python generate.py configs/demo/demo_combined.yaml --text 'a wooden boat'
python generate.py configs/demo/demo_combined.yaml --text 'a blue sofa'
python generate.py configs/demo/demo_combined.yaml --text 'sofa with legs'
python generate.py configs/demo/demo_combined.yaml --text 'a sofa with black backrest'
python generate.py configs/demo/demo_combined.yaml --text 'a small sofa'
python generate.py configs/demo/demo_combined.yaml --text 'a long brown bench'
python generate.py configs/demo/demo_combined.yaml --text 'a marble bench'
python generate.py configs/demo/demo_combined.yaml --text 'a metal bench'
python generate.py configs/demo/demo_combined.yaml --text 'concrete bench'
python generate.py configs/demo/demo_combined.yaml --text 'a military sniper rifle with long barrel'
python generate.py configs/demo/demo_combined.yaml --text 'a rifle with magazines'
python generate.py configs/demo/demo_combined.yaml --text 'a short rifle'
python generate.py configs/demo/demo_combined.yaml --text 'rifle shotgun'
python generate.py configs/demo/demo_combined.yaml --text 'a computer monitor'
python generate.py configs/demo/demo_combined.yaml --text 'a display'
python generate.py configs/demo/demo_combined.yaml --text 'a monitor with square base'