#!/bin/bash
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a TV monitor'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a glass single leg circular table' 
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a wooden double layers table'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a square metal table'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a round shaped single legged wooden table'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'this is a bar stool with metal arches as a design feature'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a children chair with little legs'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a swivel chair with wheels'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a red recliner seems confortable'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a red car'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a green SUV'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a large black truck'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a long luxury black car'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'army fighter jet'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a black airplane with long white wings'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a blue airplane with short wings'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'boeing 747'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a big ship for transportation'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a boat with sail'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a watercraft'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a wooden boat'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a blue sofa'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'sofa with legs'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a sofa with black backrest'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a small sofa'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a long brown bench'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a marble bench'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a metal bench'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'concrete bench'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a military sniper rifle with long barrel'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a rifle with magazines'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a short rifle'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'rifle shotgun'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a computer monitor'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a display'
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml --text 'a monitor with square base'