data:
  path: data/DTU
  ignore_image_idx: [3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 36, 37, 38, 39]
  classes: ['scan106']
  dataset_name: DTU
  n_views: 49
  input_type: null
  train_split: null
  val_split: null
  test_split: null
  cache_fields: True
  split_model_for_images: true
  depth_range: [0., 1400.]
model:
  c_dim: 0
  encoder: null
  patch_size: 2
  lambda_image_gradients: 1.
  lambda_sparse_depth: 1.
  lambda_normal: 0.1
training:
  out_dir:  out/multi_view_reconstruction/birds/ours_depth_sfm
  n_training_points: 2048
  n_eval_points: 16000
  model_selection_metric: mask_intersection
  model_selection_mode: maximize
  batch_size: 1
  batch_size_val: 1
  scheduler_milestones: [3000, 5000]
  scheduler_gamma: 0.5
  depth_loss_on_world_points: True
  validate_every: 5000
  visualize_every: 10000
generation:
  upsampling_steps: 4
  refinement_step: 30