data:
  dataset_name: NMR
  path: ../ShapeNet
inherit_from: configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml
generation:
  generation_dir: generation_pretrained
test:
  model_file: out/single_view_reconstruction/multi_view_supervision/ours_combined/model.pt #https://s3.eu-central-1.amazonaws.com/avg-projects/differentiable_volumetric_rendering/models/single_view_reconstruction/multi-view-supervision/ours_combined-af2bce07.pt
