inherit_from: configs/single_view_reconstruction/multi_view_supervision/ours_combined_pretrained.yaml
data:
  dataset_name: images
  path: media/demo/choy_renderings #/mnt/sdc/lzz/ShapeNet/04530566/ffacadade68cec7b926a1ee5a429907/img_choy2016/ #/mnt/sdc/lzz/diff/out/demo/ #/mnt/sdc/lzz/ShapeNet/02933112/fe8c34a5275804d451f8aaa850306632/img_choy2016/ #media/demo/choy_renderings #/mnt/sdc/lzz/diff_cup/ship_04530566/ #/mnt/sdc/lzz/ShapeNet/ #04530566/6db27ae2c9cf722d1743d8ffcf66c439/img_choy2016  #/media/demo/choy_renderings
  #dataset_name: Shapes3D 
  #path: media/demo/choy_renderings #/mnt/sdc/lzz/ShapeNet/ 
  #categories: ['02828884', '02933112', '03636649', '04090263', '04256520', '04530566']
training:
  out_dir:  out/demo/demo_combined
generation:
  generation_dir: generation
