inherit_from: configs/multi_view_reconstruction/birds/ours_depth_mvs.yaml
generation:
  generation_dir: generation_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/differentiable_volumetric_rendering/models/multi_view_reconstruction/birds/ours_depth_mvs-37d3d8ff.pt
