inherit_from: configs/multi_view_reconstruction/skull/ours_depth_sfm.yaml
generation:
  generation_dir: generation_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/differentiable_volumetric_rendering/models/multi_view_reconstruction/skull/ours_depth_sfm-6639274d.pt
