inherit_from: configs/single_view_reconstruction/multi_view_supervision/ours_depth.yaml
generation:
  generation_dir: generation_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/differentiable_volumetric_rendering/models/single_view_reconstruction/multi-view-supervision/ours_depth-64d35726.pt