inherit_from: configs/single_view_reconstruction/multi_view_supervision/ours_rgb_pretrained.yaml
data:
  dataset_name: images
  path: media/demo/kato_renderings
training:
  out_dir:  out/demo/demo_rgb
generation:
  generation_dir: generation